# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch latest changes
      run: git fetch origin main

    # - name: Determine changed files
    #   id: changed_files
    #   run: |
    #     git diff --name-only origin/main HEAD > changed_files.txt || echo "No changes"

    # - name: Upload changed files via FTP/SFTP
    #   run: |
    #     cat changed_files.txt | xargs -I {} sh -c 'mkdir -p $(dirname {}) && curl -T {} -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/test_laravel/{}'

    # - name: Cleanup
    #   run: rm changed_files.txt

    - name: Deploy via FTP/SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: '/domains/website.baleenmedia.com/public_html/'
        local-dir: './'
        exclude: '.git,.github,tests'

